"""Error code constants for postkit modules.

These constants provide autocomplete and typo-proofing when checking error codes.

Usage:
    from postkit.errors import AuthnCodes

    try:
        authn.start_impersonation(...)
    except AuthnValidationError as e:
        if e.error_code == AuthnCodes.IMPERSONATE_SELF:
            # handle self-impersonation attempt
            pass

Error code prefixes:
    VAL_     - Input shape wrong (null, format, type)
    BIZ_     - Input valid but violates domain rule
    DATA_    - Data state errors (missing, already exists)
    SESSION_ - Session state failures
    LIMIT_   - Limits/quotas exceeded
"""


class AuthnCodes:
    """Error codes for the authn module."""

    # Validation errors (VAL_)
    VAL_EMAIL_NULL = "VAL_EMAIL_NULL"
    VAL_EMAIL_EMPTY = "VAL_EMAIL_EMPTY"
    VAL_EMAIL_TOO_LONG = "VAL_EMAIL_TOO_LONG"
    VAL_EMAIL_INVALID_CHARS = "VAL_EMAIL_INVALID_CHARS"
    VAL_EMAIL_INVALID_FORMAT = "VAL_EMAIL_INVALID_FORMAT"
    VAL_HASH_NULL = "VAL_HASH_NULL"
    VAL_HASH_EMPTY = "VAL_HASH_EMPTY"
    VAL_HASH_TOO_LONG = "VAL_HASH_TOO_LONG"
    VAL_HASH_INVALID_CHARS = "VAL_HASH_INVALID_CHARS"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_SECRET_NULL = "VAL_SECRET_NULL"
    VAL_SECRET_EMPTY = "VAL_SECRET_EMPTY"
    VAL_SECRET_TOO_LONG = "VAL_SECRET_TOO_LONG"
    VAL_TOKEN_TYPE_NULL = "VAL_TOKEN_TYPE_NULL"
    VAL_TOKEN_TYPE_INVALID = "VAL_TOKEN_TYPE_INVALID"
    VAL_MFA_TYPE_NULL = "VAL_MFA_TYPE_NULL"
    VAL_MFA_TYPE_INVALID = "VAL_MFA_TYPE_INVALID"
    VAL_UUID_NULL = "VAL_UUID_NULL"
    VAL_UUID_INVALID = "VAL_UUID_INVALID"
    VAL_IP_ADDRESS_INVALID = "VAL_IP_ADDRESS_INVALID"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"
    VAL_REASON_REQUIRED = "VAL_REASON_REQUIRED"
    VAL_DURATION_POSITIVE = "VAL_DURATION_POSITIVE"

    # Session errors (SESSION_)
    SESSION_INVALID = "SESSION_INVALID"
    SESSION_ACTOR_INVALID = "SESSION_ACTOR_INVALID"
    SESSION_TARGET_INVALID = "SESSION_TARGET_INVALID"
    SESSION_OPERATOR_INVALID = "SESSION_OPERATOR_INVALID"

    # Business logic errors (BIZ_)
    BIZ_IMPERSONATE_SELF = "BIZ_IMPERSONATE_SELF"
    BIZ_IMPERSONATE_CHAIN = "BIZ_IMPERSONATE_CHAIN"

    # Limit errors (LIMIT_)
    LIMIT_DURATION_EXCEEDED = "LIMIT_DURATION_EXCEEDED"


class AuthzCodes:
    """Error codes for the authz module."""

    # Validation errors (VAL_)
    VAL_IDENTIFIER_NULL = "VAL_IDENTIFIER_NULL"
    VAL_IDENTIFIER_EMPTY = "VAL_IDENTIFIER_EMPTY"
    VAL_IDENTIFIER_TOO_LONG = "VAL_IDENTIFIER_TOO_LONG"
    VAL_IDENTIFIER_FORMAT = "VAL_IDENTIFIER_FORMAT"
    VAL_ID_NULL = "VAL_ID_NULL"
    VAL_ID_EMPTY = "VAL_ID_EMPTY"
    VAL_ID_TOO_LONG = "VAL_ID_TOO_LONG"
    VAL_ID_INVALID_CHARS = "VAL_ID_INVALID_CHARS"
    VAL_ID_WHITESPACE = "VAL_ID_WHITESPACE"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_ARRAY_ELEMENT_INVALID = "VAL_ARRAY_ELEMENT_INVALID"
    VAL_EXPIRATION_FUTURE = "VAL_EXPIRATION_FUTURE"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"

    # Business logic errors (BIZ_)
    BIZ_SELF_MEMBERSHIP = "BIZ_SELF_MEMBERSHIP"
    BIZ_CYCLE_GROUP = "BIZ_CYCLE_GROUP"
    BIZ_SELF_PARENT = "BIZ_SELF_PARENT"
    BIZ_CYCLE_RESOURCE = "BIZ_CYCLE_RESOURCE"
    BIZ_CYCLE_HIERARCHY = "BIZ_CYCLE_HIERARCHY"
    BIZ_CYCLE_SELF = "BIZ_CYCLE_SELF"
    BIZ_BULK_GROUP_MEMBERSHIP = "BIZ_BULK_GROUP_MEMBERSHIP"
    BIZ_BULK_PARENT_RELATION = "BIZ_BULK_PARENT_RELATION"
    BIZ_GRANT_NO_EXPIRATION = "BIZ_GRANT_NO_EXPIRATION"

    # Data state errors (DATA_)
    DATA_GRANT_NOT_FOUND = "DATA_GRANT_NOT_FOUND"


class ConfigCodes:
    """Error codes for the config module."""

    # Validation errors (VAL_)
    VAL_KEY_NULL = "VAL_KEY_NULL"
    VAL_KEY_EMPTY = "VAL_KEY_EMPTY"
    VAL_KEY_TOO_LONG = "VAL_KEY_TOO_LONG"
    VAL_KEY_FORMAT = "VAL_KEY_FORMAT"
    VAL_KEY_SLASHES = "VAL_KEY_SLASHES"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_PATTERN_NULL = "VAL_PATTERN_NULL"
    VAL_PATTERN_EMPTY = "VAL_PATTERN_EMPTY"
    VAL_PATTERN_TOO_LONG = "VAL_PATTERN_TOO_LONG"
    VAL_PATTERN_FORMAT = "VAL_PATTERN_FORMAT"
    VAL_PATTERN_SLASHES = "VAL_PATTERN_SLASHES"
    VAL_SCHEMA_NULL = "VAL_SCHEMA_NULL"
    VAL_KEEP_VERSIONS_NEGATIVE = "VAL_KEEP_VERSIONS_NEGATIVE"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"

    # Business logic errors (BIZ_)
    BIZ_DELETE_ACTIVE_VERSION = "BIZ_DELETE_ACTIVE_VERSION"


class MeterCodes:
    """Error codes for the meter module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_EVENT_TYPE_NULL = "VAL_EVENT_TYPE_NULL"
    VAL_EVENT_TYPE_EMPTY = "VAL_EVENT_TYPE_EMPTY"
    VAL_EVENT_TYPE_TOO_LONG = "VAL_EVENT_TYPE_TOO_LONG"
    VAL_UNIT_NULL = "VAL_UNIT_NULL"
    VAL_UNIT_EMPTY = "VAL_UNIT_EMPTY"
    VAL_UNIT_TOO_LONG = "VAL_UNIT_TOO_LONG"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"
    VAL_USER_ID_REQUIRED = "VAL_USER_ID_REQUIRED"
    VAL_TTL_OUT_OF_RANGE = "VAL_TTL_OUT_OF_RANGE"
    VAL_AMOUNT_NEGATIVE = "VAL_AMOUNT_NEGATIVE"
    VAL_ADJUSTMENT_ZERO = "VAL_ADJUSTMENT_ZERO"
    VAL_ALLOCATION_REQUIRED = "VAL_ALLOCATION_REQUIRED"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"
    VAL_MONTHS_MIN = "VAL_MONTHS_MIN"

    # Business logic errors (BIZ_)
    BIZ_LEDGER_IMMUTABLE = "BIZ_LEDGER_IMMUTABLE"

    # Data state errors (DATA_)
    DATA_ACCOUNT_NOT_FOUND = "DATA_ACCOUNT_NOT_FOUND"
