"""Error code constants for postkit modules.

These constants provide autocomplete and typo-proofing when checking error codes.

Usage:
    from postkit.authn import AuthnErrorCode

    try:
        authn.start_impersonation(...)
    except AuthnValidationError as e:
        if e.error_code == AuthnErrorCode.BIZ_IMPERSONATE_SELF:
            # handle self-impersonation attempt
            pass

Error code prefixes:
    VAL_     - Input shape wrong (null, format, type)
    BIZ_     - Input valid but violates domain rule
    DATA_    - Data state errors (missing, already exists)
    SESSION_ - Session state failures
    LIMIT_   - Limits/quotas exceeded
    CRED_    - Credential state errors
"""


class AuthnErrorCode:
    """Error codes for the authn module."""

    # Validation errors (VAL_)
    VAL_EMAIL_NULL = "VAL_EMAIL_NULL"
    VAL_EMAIL_EMPTY = "VAL_EMAIL_EMPTY"
    VAL_EMAIL_TOO_LONG = "VAL_EMAIL_TOO_LONG"
    VAL_EMAIL_INVALID_CHARS = "VAL_EMAIL_INVALID_CHARS"
    VAL_EMAIL_INVALID_FORMAT = "VAL_EMAIL_INVALID_FORMAT"
    VAL_HASH_NULL = "VAL_HASH_NULL"
    VAL_HASH_EMPTY = "VAL_HASH_EMPTY"
    VAL_HASH_TOO_LONG = "VAL_HASH_TOO_LONG"
    VAL_HASH_INVALID_CHARS = "VAL_HASH_INVALID_CHARS"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_SECRET_NULL = "VAL_SECRET_NULL"
    VAL_SECRET_EMPTY = "VAL_SECRET_EMPTY"
    VAL_SECRET_TOO_LONG = "VAL_SECRET_TOO_LONG"
    VAL_TOKEN_TYPE_NULL = "VAL_TOKEN_TYPE_NULL"
    VAL_TOKEN_TYPE_INVALID = "VAL_TOKEN_TYPE_INVALID"
    VAL_CREDENTIAL_TYPE_NULL = "VAL_CREDENTIAL_TYPE_NULL"
    VAL_CREDENTIAL_TYPE_INVALID = "VAL_CREDENTIAL_TYPE_INVALID"
    VAL_UUID_NULL = "VAL_UUID_NULL"
    VAL_UUID_INVALID = "VAL_UUID_INVALID"
    VAL_IP_ADDRESS_INVALID = "VAL_IP_ADDRESS_INVALID"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"
    VAL_REASON_REQUIRED = "VAL_REASON_REQUIRED"
    VAL_DURATION_POSITIVE = "VAL_DURATION_POSITIVE"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"

    # Session errors (SESSION_)
    SESSION_INVALID = "SESSION_INVALID"
    SESSION_ACTOR_INVALID = "SESSION_ACTOR_INVALID"
    SESSION_TARGET_INVALID = "SESSION_TARGET_INVALID"
    SESSION_OPERATOR_INVALID = "SESSION_OPERATOR_INVALID"

    # Business logic errors (BIZ_)
    BIZ_IMPERSONATE_SELF = "BIZ_IMPERSONATE_SELF"
    BIZ_IMPERSONATE_CHAIN = "BIZ_IMPERSONATE_CHAIN"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"

    # Credential state errors (CRED_)
    CRED_NO_MATERIAL = "CRED_NO_MATERIAL"
    CRED_DISABLE_NO_REASON = "CRED_DISABLE_NO_REASON"

    # User state errors
    USER_DISABLED = "USER_DISABLED"

    # Limit errors (LIMIT_)
    LIMIT_DURATION_EXCEEDED = "LIMIT_DURATION_EXCEEDED"


class AuthzErrorCode:
    """Error codes for the authz module."""

    # Validation errors (VAL_)
    VAL_IDENTIFIER_NULL = "VAL_IDENTIFIER_NULL"
    VAL_IDENTIFIER_EMPTY = "VAL_IDENTIFIER_EMPTY"
    VAL_IDENTIFIER_TOO_LONG = "VAL_IDENTIFIER_TOO_LONG"
    VAL_IDENTIFIER_FORMAT = "VAL_IDENTIFIER_FORMAT"
    VAL_ID_NULL = "VAL_ID_NULL"
    VAL_ID_EMPTY = "VAL_ID_EMPTY"
    VAL_ID_TOO_LONG = "VAL_ID_TOO_LONG"
    VAL_ID_INVALID_CHARS = "VAL_ID_INVALID_CHARS"
    VAL_ID_WHITESPACE = "VAL_ID_WHITESPACE"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_ARRAY_ELEMENT_INVALID = "VAL_ARRAY_ELEMENT_INVALID"
    VAL_EXPIRATION_FUTURE = "VAL_EXPIRATION_FUTURE"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"

    # Business logic errors (BIZ_)
    BIZ_SELF_MEMBERSHIP = "BIZ_SELF_MEMBERSHIP"
    BIZ_CYCLE_GROUP = "BIZ_CYCLE_GROUP"
    BIZ_SELF_PARENT = "BIZ_SELF_PARENT"
    BIZ_CYCLE_RESOURCE = "BIZ_CYCLE_RESOURCE"
    BIZ_CYCLE_HIERARCHY = "BIZ_CYCLE_HIERARCHY"
    BIZ_CYCLE_SELF = "BIZ_CYCLE_SELF"
    BIZ_BULK_GROUP_MEMBERSHIP = "BIZ_BULK_GROUP_MEMBERSHIP"
    BIZ_BULK_PARENT_RELATION = "BIZ_BULK_PARENT_RELATION"
    BIZ_GRANT_NO_EXPIRATION = "BIZ_GRANT_NO_EXPIRATION"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"

    # Data state errors (DATA_)
    DATA_GRANT_NOT_FOUND = "DATA_GRANT_NOT_FOUND"


class ConfigErrorCode:
    """Error codes for the config module."""

    # Validation errors (VAL_)
    VAL_KEY_NULL = "VAL_KEY_NULL"
    VAL_KEY_EMPTY = "VAL_KEY_EMPTY"
    VAL_KEY_TOO_LONG = "VAL_KEY_TOO_LONG"
    VAL_KEY_FORMAT = "VAL_KEY_FORMAT"
    VAL_KEY_SLASHES = "VAL_KEY_SLASHES"
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_PATTERN_NULL = "VAL_PATTERN_NULL"
    VAL_PATTERN_EMPTY = "VAL_PATTERN_EMPTY"
    VAL_PATTERN_TOO_LONG = "VAL_PATTERN_TOO_LONG"
    VAL_PATTERN_FORMAT = "VAL_PATTERN_FORMAT"
    VAL_PATTERN_SLASHES = "VAL_PATTERN_SLASHES"
    VAL_SCHEMA_NULL = "VAL_SCHEMA_NULL"
    VAL_KEEP_VERSIONS_NEGATIVE = "VAL_KEEP_VERSIONS_NEGATIVE"
    VAL_YEAR_OUT_OF_RANGE = "VAL_YEAR_OUT_OF_RANGE"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"

    # Business logic errors (BIZ_)
    BIZ_DELETE_ACTIVE_VERSION = "BIZ_DELETE_ACTIVE_VERSION"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"


class LeaseErrorCode:
    """Error codes for the lease module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_LEASE_NAME_NULL = "VAL_LEASE_NAME_NULL"
    VAL_LEASE_NAME_EMPTY = "VAL_LEASE_NAME_EMPTY"
    VAL_LEASE_NAME_TOO_LONG = "VAL_LEASE_NAME_TOO_LONG"
    VAL_LEASE_NAME_INVALID_CHARS = "VAL_LEASE_NAME_INVALID_CHARS"
    VAL_LEASE_NAME_WHITESPACE = "VAL_LEASE_NAME_WHITESPACE"
    VAL_HOLDER_NULL = "VAL_HOLDER_NULL"
    VAL_HOLDER_EMPTY = "VAL_HOLDER_EMPTY"
    VAL_HOLDER_TOO_LONG = "VAL_HOLDER_TOO_LONG"
    VAL_HOLDER_INVALID_CHARS = "VAL_HOLDER_INVALID_CHARS"
    VAL_HOLDER_WHITESPACE = "VAL_HOLDER_WHITESPACE"
    VAL_TTL_NOT_POSITIVE = "VAL_TTL_NOT_POSITIVE"
    VAL_TTL_EXCEEDS_MAX = "VAL_TTL_EXCEEDS_MAX"
    VAL_FENCE_NULL = "VAL_FENCE_NULL"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"
    VAL_PRUNE_INTERVAL_NOT_POSITIVE = "VAL_PRUNE_INTERVAL_NOT_POSITIVE"

    # Fencing (raised with SQLSTATE 40001, serialization_failure)
    FENCE_STALE = "FENCE_STALE"

    # Internal errors (INT_)
    INT_COUNTER_MISSING = "INT_COUNTER_MISSING"

    # Business logic errors (BIZ_)
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"


class MeterErrorCode:
    """Error codes for the meter module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_EVENT_TYPE_NULL = "VAL_EVENT_TYPE_NULL"
    VAL_EVENT_TYPE_EMPTY = "VAL_EVENT_TYPE_EMPTY"
    VAL_EVENT_TYPE_TOO_LONG = "VAL_EVENT_TYPE_TOO_LONG"
    VAL_UNIT_NULL = "VAL_UNIT_NULL"
    VAL_UNIT_EMPTY = "VAL_UNIT_EMPTY"
    VAL_UNIT_TOO_LONG = "VAL_UNIT_TOO_LONG"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"
    VAL_USER_ID_REQUIRED = "VAL_USER_ID_REQUIRED"
    VAL_TTL_OUT_OF_RANGE = "VAL_TTL_OUT_OF_RANGE"
    VAL_AMOUNT_NEGATIVE = "VAL_AMOUNT_NEGATIVE"
    VAL_ADJUSTMENT_ZERO = "VAL_ADJUSTMENT_ZERO"
    VAL_ALLOCATION_REQUIRED = "VAL_ALLOCATION_REQUIRED"
    VAL_MONTH_OUT_OF_RANGE = "VAL_MONTH_OUT_OF_RANGE"
    VAL_MONTHS_MIN = "VAL_MONTHS_MIN"

    # Business logic errors (BIZ_)
    BIZ_LEDGER_IMMUTABLE = "BIZ_LEDGER_IMMUTABLE"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"
    BIZ_ALL_NAMESPACES_REQUIRES_BYPASS = "BIZ_ALL_NAMESPACES_REQUIRES_BYPASS"

    # Data state errors (DATA_)
    DATA_ACCOUNT_NOT_FOUND = "DATA_ACCOUNT_NOT_FOUND"


class OutboxErrorCode:
    """Error codes for the outbox module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_TOPIC_NULL = "VAL_TOPIC_NULL"
    VAL_TOPIC_EMPTY = "VAL_TOPIC_EMPTY"
    VAL_TOPIC_TOO_LONG = "VAL_TOPIC_TOO_LONG"
    VAL_TOPIC_RESERVED = "VAL_TOPIC_RESERVED"
    VAL_TOPIC_FORMAT = "VAL_TOPIC_FORMAT"
    VAL_CONSUMER_NULL = "VAL_CONSUMER_NULL"
    VAL_CONSUMER_EMPTY = "VAL_CONSUMER_EMPTY"
    VAL_CONSUMER_TOO_LONG = "VAL_CONSUMER_TOO_LONG"
    VAL_CONSUMER_FORMAT = "VAL_CONSUMER_FORMAT"
    VAL_EVENT_TYPE_NULL = "VAL_EVENT_TYPE_NULL"
    VAL_EVENT_TYPE_EMPTY = "VAL_EVENT_TYPE_EMPTY"
    VAL_EVENT_TYPE_TOO_LONG = "VAL_EVENT_TYPE_TOO_LONG"
    VAL_EVENT_TYPE_FORMAT = "VAL_EVENT_TYPE_FORMAT"
    VAL_PAYLOAD_NULL = "VAL_PAYLOAD_NULL"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"
    VAL_POSITION_INVALID = "VAL_POSITION_INVALID"
    VAL_SUBSCRIBE_FROM_REQUIRED = "VAL_SUBSCRIBE_FROM_REQUIRED"
    VAL_TRIM_INTERVAL_NOT_POSITIVE = "VAL_TRIM_INTERVAL_NOT_POSITIVE"

    # Business logic errors (BIZ_)
    BIZ_CONSUMER_EXISTS = "BIZ_CONSUMER_EXISTS"
    BIZ_CONSUMER_UNKNOWN = "BIZ_CONSUMER_UNKNOWN"
    BIZ_CURSOR_LOST = "BIZ_CURSOR_LOST"
    BIZ_POSITION_BEYOND_HEAD = "BIZ_POSITION_BEYOND_HEAD"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"
    BIZ_ALL_NAMESPACES_REQUIRES_BYPASS = "BIZ_ALL_NAMESPACES_REQUIRES_BYPASS"


class PresenceErrorCode:
    """Error codes for the presence module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_ENTITY_NULL = "VAL_ENTITY_NULL"
    VAL_ENTITY_EMPTY = "VAL_ENTITY_EMPTY"
    VAL_ENTITY_TOO_LONG = "VAL_ENTITY_TOO_LONG"
    VAL_ENTITY_INVALID_CHARS = "VAL_ENTITY_INVALID_CHARS"
    VAL_ENTITY_WHITESPACE = "VAL_ENTITY_WHITESPACE"
    VAL_ENTITIES_NULL = "VAL_ENTITIES_NULL"
    VAL_KIND_NULL = "VAL_KIND_NULL"
    VAL_KIND_EMPTY = "VAL_KIND_EMPTY"
    VAL_KIND_TOO_LONG = "VAL_KIND_TOO_LONG"
    VAL_KIND_FORMAT = "VAL_KIND_FORMAT"
    VAL_TIMEOUT_NOT_POSITIVE = "VAL_TIMEOUT_NOT_POSITIVE"
    VAL_STATUS_INVALID = "VAL_STATUS_INVALID"
    VAL_TRIM_INTERVAL_NOT_POSITIVE = "VAL_TRIM_INTERVAL_NOT_POSITIVE"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"

    # Business logic errors
    ENTITY_UNKNOWN = "ENTITY_UNKNOWN"
    HOOK_QUEUE_MISSING = "HOOK_QUEUE_MISSING"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"
    BIZ_ALL_NAMESPACES_REQUIRES_BYPASS = "BIZ_ALL_NAMESPACES_REQUIRES_BYPASS"


class QueueErrorCode:
    """Error codes for the queue module."""

    # Validation errors (VAL_)
    VAL_NAMESPACE_NULL = "VAL_NAMESPACE_NULL"
    VAL_NAMESPACE_EMPTY = "VAL_NAMESPACE_EMPTY"
    VAL_NAMESPACE_TOO_LONG = "VAL_NAMESPACE_TOO_LONG"
    VAL_NAMESPACE_INVALID_CHARS = "VAL_NAMESPACE_INVALID_CHARS"
    VAL_NAMESPACE_WHITESPACE = "VAL_NAMESPACE_WHITESPACE"
    VAL_QUEUE_NULL = "VAL_QUEUE_NULL"
    VAL_QUEUE_EMPTY = "VAL_QUEUE_EMPTY"
    VAL_QUEUE_TOO_LONG = "VAL_QUEUE_TOO_LONG"
    VAL_QUEUE_FORMAT = "VAL_QUEUE_FORMAT"
    VAL_PAYLOAD_NULL = "VAL_PAYLOAD_NULL"
    VAL_PRIORITY_RANGE = "VAL_PRIORITY_RANGE"
    VAL_NOT_POSITIVE = "VAL_NOT_POSITIVE"
    VAL_JOB_ID_NULL = "VAL_JOB_ID_NULL"
    VAL_EXTENSION_POSITIVE = "VAL_EXTENSION_POSITIVE"
    VAL_WORKER_ID_NULL = "VAL_WORKER_ID_NULL"
    VAL_DEAD_LETTER_ID_NULL = "VAL_DEAD_LETTER_ID_NULL"
    VAL_SCHEDULE_NAME_NULL = "VAL_SCHEDULE_NAME_NULL"
    VAL_SCHEDULE_NAME_EMPTY = "VAL_SCHEDULE_NAME_EMPTY"
    VAL_SCHEDULE_NAME_TOO_LONG = "VAL_SCHEDULE_NAME_TOO_LONG"
    VAL_SCHEDULE_NAME_FORMAT = "VAL_SCHEDULE_NAME_FORMAT"
    VAL_CRON_EMPTY = "VAL_CRON_EMPTY"
    VAL_CRON_FIELDS = "VAL_CRON_FIELDS"
    VAL_CRON_INVALID = "VAL_CRON_INVALID"

    # Business logic errors (BIZ_)
    BIZ_JOB_NOT_RUNNING = "BIZ_JOB_NOT_RUNNING"
    BIZ_JOB_NOT_YOURS = "BIZ_JOB_NOT_YOURS"
    BIZ_SCHEDULE_DUPLICATE = "BIZ_SCHEDULE_DUPLICATE"
    BIZ_SCHEDULE_REQUIRES_SCHEDULE = "BIZ_SCHEDULE_REQUIRES_SCHEDULE"
    BIZ_SCHEDULE_CRON_AND_INTERVAL = "BIZ_SCHEDULE_CRON_AND_INTERVAL"
    BIZ_DEAD_LETTER_ALREADY_RETRIED = "BIZ_DEAD_LETTER_ALREADY_RETRIED"
    BIZ_RLS_NOT_ACTIVE = "BIZ_RLS_NOT_ACTIVE"
    BIZ_ALL_NAMESPACES_REQUIRES_BYPASS = "BIZ_ALL_NAMESPACES_REQUIRES_BYPASS"

    # Data state errors (DATA_)
    DATA_JOB_NOT_FOUND = "DATA_JOB_NOT_FOUND"
    DATA_DEAD_LETTER_NOT_FOUND = "DATA_DEAD_LETTER_NOT_FOUND"
